name: Build Vue Example App

on: push

jobs:
  firebase-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
      - name: Installing project dependencies
      - run: npm install
      - name: Building the project
      - run: npm run build
